#stages:
#  - install_dependencies
#  - test
#
#image: python:3-alpine
#
#system_deps:
#  stage: install_dependencies
#  script:
#    - apk add make
#
#python_deps:
#  stage: install_dependencies
#  script:
#    - python3 -m pip install -r requirements.txt
#
#python_dev_deps:
#  stage: install_dependencies
#  script:
#    - python3 -m pip install -r requirements-dev.txt
#
#test:
#  stage: test
#  script:
#    - make testv2


stages:
  - test

image: python:3-alpine

system_deps:
  stage: test
  script:
    - apk add make

python_deps:
  stage: test
  script:
    - python3 -m pip install -r requirements.txt

python_dev_deps:
  stage: test
  script:
    - python3 -m pip install -r requirements-dev.txt

test:
  stage: test
  script:
    - make testv2
