repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-builtin-literals
      - id: double-quote-string-fixer

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: make fix-isort
        types: [ python ]
        language: system


#  - repo: local
#    hooks:
#      - id: flake8
#        name: flake8
#        entry: make check-flake8
#        types: [ python ]
#        language: system
