name: ci

on:
  push:
#    branches:
#      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: test
        run: python3 -m pytest tests

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: tandav/notes

  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: 'curl -X POST -H "token: ${{ secrets.RESTART_HOOK_TOKEN }}" ${{ secrets.RESTART_HOOK_URL }}'
